name: Test

on:
  pull_request: {}
  push: { branches: [master] }

jobs:
  build:
    name: Test project
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.14f1
        include:
          - unityVersion: 2019.4.14f1 
            projectPath: Tests/Project 
            testMode: playmode # editmode
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{matrix.projectPath}}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.6
        with:
          projectPath: ${{matrix.projectPath}}
          unityVersion: ${{matrix.unityVersion}}
          testMode: ${{matrix.testMode}}
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE }}

      # Upload Test Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          path: ${{steps.tests.outputs.artifactsPath}}